name: Build Plugin JAR
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21 }
      - name: Build
        run: ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with: { name: TALUltimate, path: build/libs/*.jar }
